
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intelligentdorm?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  banner:
    image:
      width: 200
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/swagger3
mybatis:
  type-aliases-package: com.moyu.nicespring.entity
  mapper-locations: classpath:mapper/*.xml
web:
  upload:
    path: F:/store
pagehelper:
    helperDialect: mysql
    reasonable: true
    pageSizeZero: true
    params: count=countSql
    support-methods-arguments: true
encrypt: moyuno1